import {useEffect, useRef, useState, type FormEvent} from 'react';
import {Plus, Pencil, Play, Pause, RotateCcw, Trash2} from 'lucide-react';

type Entry={id:string;name:string;project:string};
type Expert=Entry & {revision:number;specialty:string;email:string;auth_id:string;active:boolean};
type Agenda={name:string;minutes:number;notes:string;done:boolean};
type Meeting={id:string;name:string;start:string;duration:number;expert:string;assignee:string;link:string;confirmation:string;agenda:Agenda[];conclusion:string;actions:string;closed:boolean};
type CoachingSession=Entry & {revision:number;units:string[];objective:string;meetings:Meeting[]};
type Data={sessions:CoachingSession[];experts:Expert[]};
type Props={api:(op:string,data?:unknown)=>Promise<Data>;projects:Entry[];units:Entry[];items:(Entry & {unit:string;status:string})[];manage:boolean;canRun:boolean;open:(id:string)=>void;delivery:()=>void};

export default function CoachingSessions({api,projects,units,items,manage,canRun,open,delivery}:Props){
 const [data,setData]=useState<Data>({sessions:[],experts:[]});
 const [selected,setSelected]=useState('');
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(false);
 const [editor,setEditor]=useState<'expert'|'session'|null>(null);
 const [expert,setExpert]=useState<Expert|null>(null);
 const [project,setProject]=useState(projects[0]?.id||'');
 const sending=useRef(false);
 const load=async()=>{setData(await api('coaching-sessions'));setLoaded(true);};
 useEffect(()=>{let live=true;setLoaded(false);setData({sessions:[],experts:[]});api('coaching-sessions').then(d=>{if(live){setData(d);setLoaded(true);}}).catch(e=>{if(live)setError(String(e.message));});return()=>{live=false;};},[api]);
 const mutate=async(op:string,body:Record<string,unknown>)=>{if(sending.current)return false;sending.current=true;setError('');setBusy(true);try{await api(op,body);await load();return true;}catch(e){setError(e instanceof Error?e.message:'Không lưu được');return false;}finally{sending.current=false;setBusy(false);}};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const values=Object.fromEntries(f);const ok=await mutate(editor==='expert'?'coach-profile':'coaching-session-save',editor==='expert'?{...values,id:expert?.id,revision:expert?.revision,active:f.get('active')==='on'}:{...values,units:f.getAll('units')});if(ok){setEditor(null);setExpert(null);}};
 const current=data.sessions.find(s=>s.id===selected)||data.sessions[0];
 return <>
  {error&&<p role="alert" className="vc-warning">{error} <button disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>Tải lại</button></p>}
  <section className="vc-card"><div className="vc-row spread"><h2>Chuyên gia</h2>{manage&&<button disabled={busy} onClick={()=>{setExpert(null);setProject(projects[0]?.id||'');setEditor('expert');}}><Plus size={16}/> Thêm chuyên gia</button>}</div>
   {data.experts.map(x=><article className="vc-source" key={x.id}><div className="vc-row spread"><h3>{x.name}</h3>{manage&&<button aria-label={'Sửa '+x.name} onClick={()=>{setExpert(x);setProject(x.project);setEditor('expert');}}><Pencil size={16}/></button>}</div><p>{x.specialty}</p><p>{x.email}</p>{!x.active&&<span>Ngừng hoạt động</span>}</article>)}{loaded&&!data.experts.length&&<p>Chưa có chuyên gia.</p>}
  </section>
  {editor&&<section className="vc-card"><form onSubmit={e=>void submit(e)} key={editor+(expert?.id||'new')}><h2>{editor==='expert'?'Hồ sơ chuyên gia':'Thêm phiên khai vấn'}</h2><fieldset disabled={busy}><label>Dự án<select name="project" required value={project} onChange={e=>setProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Tên<input name="name" required maxLength={500} defaultValue={expert?.name}/></label>
   {editor==='expert'?<><label>Chuyên môn<textarea name="specialty" maxLength={4000} defaultValue={expert?.specialty}/></label><label>Email<input name="email" type="email" defaultValue={expert?.email}/></label><label>Mã tài khoản được phân công<input name="auth_id" defaultValue={expert?.auth_id}/></label><label><input name="active" type="checkbox" defaultChecked={expert?.active!==false}/> Hoạt động</label></>:<><label>Mục tiêu<textarea name="objective" maxLength={10000}/></label><fieldset><legend>Đơn vị tham gia</legend>{units.filter(u=>u.project===project).map(u=><label className="vc-checkbox" key={u.id}><input type="checkbox" name="units" value={u.id}/>{u.name}</label>)}</fieldset></>}
   <div className="vc-row"><button className="primary" type="submit">Lưu</button><button type="button" onClick={()=>{setEditor(null);setExpert(null);}}>Hủy</button></div></fieldset></form></section>}
  <section className="vc-card"><div className="vc-row spread"><h2>Phiên khai vấn</h2>{manage&&<button disabled={busy} onClick={()=>{setExpert(null);setProject(projects[0]?.id||'');setEditor('session');}}><Plus size={16}/> Thêm phiên</button>}</div><nav className="vc-row" aria-label="Chọn phiên">{data.sessions.map(s=><button key={s.id} aria-pressed={s.id===current?.id} onClick={()=>setSelected(s.id)}>{s.name}</button>)}</nav>{!loaded&&!error&&<p role="status">Đang tải…</p>}{loaded&&!current&&<p>Chưa có phiên khai vấn.</p>}</section>
  {current&&<SessionPanel key={current.id} session={current} experts={data.experts} units={units} items={items} manage={manage} canRun={canRun} busy={busy} mutate={mutate} open={open} delivery={delivery}/>}
 </>;
}

function SessionPanel({session:s,experts,units,items,manage,canRun,busy,mutate,open,delivery}:{session:CoachingSession;experts:Expert[];units:Entry[];items:Props['items'];manage:boolean;canRun:boolean;busy:boolean;mutate:(op:string,data:Record<string,unknown>)=>Promise<boolean>;open:Props['open'];delivery:Props['delivery']}){
 const [tab,setTab]=useState('prepare');const [meetingId,setMeetingId]=useState('');const [editing,setEditing]=useState<Meeting|null|undefined>();
 const meeting=s.meetings.find(m=>m.id===meetingId)||s.meetings[0];
 const scoped=items.filter(i=>s.units.includes(i.unit));
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const values=Object.fromEntries(f);const date=new Date(String(values.start));if(Number.isNaN(date.getTime()))return;const ok=await mutate('coaching-meeting-save',{...values,id:s.id,revision:s.revision,meeting_id:editing?.id,start:date.toISOString(),duration:Number(values.duration)});if(ok)setEditing(undefined);};
 const localStart=(value:string)=>{const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16);};
 return <section className="vc-card"><div className="vc-row spread"><h2>{s.name}</h2>{manage&&<button disabled={busy} onClick={()=>setEditing(null)}><Plus size={16}/> Thêm buổi</button>}</div><p>{s.objective}</p><p>{units.filter(u=>s.units.includes(u.id)).map(u=>u.name).join(' · ')}</p>
  <nav className="vc-row" aria-label="Giai đoạn phiên">{[['prepare','Chuẩn bị'],['live','Thực hiện'],['after','Sau khai vấn']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
  {editing!==undefined&&<form onSubmit={e=>void submit(e)} key={editing?.id||'new'}><fieldset disabled={busy}><legend>{editing?'Sửa buổi':'Thêm buổi'}</legend><label>Tên buổi<input name="name" required defaultValue={editing?.name}/></label><label>Bắt đầu<input name="start" type="datetime-local" required defaultValue={editing?localStart(editing.start):''}/></label><label>Thời lượng (phút)<input name="duration" type="number" min={15} max={480} required defaultValue={editing?.duration||90}/></label><label>Chuyên gia<select name="expert" required defaultValue={editing?.expert||''}><option value="">Chọn chuyên gia</option>{experts.filter(x=>x.project===s.project&&x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Liên kết phòng<input type="url" name="link" defaultValue={editing?.link}/></label><button className="primary" type="submit">Lưu lịch</button><button type="button" onClick={()=>setEditing(undefined)}>Hủy</button></fieldset></form>}
  <nav className="vc-row" aria-label="Chọn buổi">{s.meetings.map(m=><button key={m.id} aria-pressed={meeting?.id===m.id} onClick={()=>setMeetingId(m.id)}>{m.name} · {new Date(m.start).toLocaleString('vi-VN')}</button>)}</nav>
  {meeting&&<div className="vc-row"><span>{meeting.duration} phút · {experts.find(x=>x.id===meeting.expert)?.name} · {meeting.confirmation==='confirmed'?'Đã xác nhận':'Chờ xác nhận'}</span>{meeting.link&&<a href={meeting.link} target="_blank" rel="noreferrer">Mở phòng</a>}{manage&&<button onClick={()=>setEditing(meeting)}><Pencil size={16}/> Sửa lịch</button>}{canRun&&meeting.confirmation!=='confirmed'&&<button disabled={busy} onClick={()=>void mutate('coaching-meeting-confirm',{id:s.id,revision:s.revision,meeting_id:meeting.id})}>Xác nhận lịch</button>}</div>}
  {tab==='prepare'&&<div>{scoped.map(i=><article key={i.id} className="vc-source"><h3>{i.name}</h3><button onClick={()=>open(i.id)}>Mở hồ sơ</button></article>)}{!scoped.length&&<p>Chưa có sáng kiến trong phạm vi phiên.</p>}</div>}
  {tab==='live'&&(meeting?<MeetingNotes key={meeting.id+':'+s.revision} meeting={meeting} disabled={!canRun||busy} save={body=>mutate('coaching-meeting-notes',{...body,id:s.id,revision:s.revision,meeting_id:meeting.id})}/>:<p>Chưa có buổi khai vấn.</p>)}
  {tab==='after'&&<><h3>Kết luận & hành động</h3>{s.meetings.map(m=><article className="vc-source" key={m.id}><h4>{m.name}</h4><p className="vc-answer">{m.conclusion}</p><p className="vc-answer">{m.actions}</p><span>{m.closed?'Đã chốt':'Chưa chốt'}</span></article>)}<button onClick={delivery}>Hồ sơ sau khai vấn</button></>}
 </section>;
}

function MeetingNotes({meeting,disabled,save}:{meeting:Meeting;disabled:boolean;save:(body:Record<string,unknown>)=>Promise<boolean>}){
 const [agenda,setAgendaState]=useState(meeting.agenda);const [seconds,setSeconds]=useState(0);const [running,setRunning]=useState(false);
 const elapsed=useRef(0);const form=useRef<HTMLFormElement>(null);const [dirty,setDirty]=useState(false);
 const setAgenda=(next:Agenda[])=>{setAgendaState(next);setDirty(true);};
 useEffect(()=>{if(!running)return;const start=Date.now()-elapsed.current*1000;const timer=setInterval(()=>{elapsed.current=Math.floor((Date.now()-start)/1000);setSeconds(elapsed.current);},250);return()=>clearInterval(timer);},[running]);
 useEffect(()=>{if(!dirty)return;const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};const leave=(e:MouseEvent)=>{if(!form.current?.contains(e.target as Node)&&(e.target as Element).closest('button,a,select')&&!window.confirm('Nội dung buổi chưa lưu. Rời màn hình và bỏ thay đổi?')){e.preventDefault();e.stopPropagation();}};window.addEventListener('beforeunload',unload);document.addEventListener('click',leave,true);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',leave,true);};},[dirty]);
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({...Object.fromEntries(f),agenda,closed:f.get('closed')==='on'});};
 return <form ref={form} onChange={()=>setDirty(true)} onSubmit={submit}><div className="vc-row"><output aria-label="Thời gian đã trôi">{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</output><button disabled={disabled} type="button" onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>} {running?'Tạm dừng':'Bắt đầu'}</button><button disabled={disabled} type="button" onClick={()=>{setRunning(false);elapsed.current=0;setSeconds(0);}}><RotateCcw size={16}/> Đặt lại</button></div><fieldset disabled={disabled}><legend>Chương trình buổi</legend>{agenda.map((a,i)=><div className="vc-source" key={i}><label>Nội dung<input required value={a.name} onChange={e=>setAgenda(agenda.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/></label><label>Phút<input type="number" min={1} max={480} required value={a.minutes} onChange={e=>setAgenda(agenda.map((x,j)=>j===i?{...x,minutes:Number(e.target.value)}:x))}/></label><label>Ghi chú<textarea value={a.notes} onChange={e=>setAgenda(agenda.map((x,j)=>j===i?{...x,notes:e.target.value}:x))}/></label><label><input type="checkbox" checked={a.done} onChange={e=>setAgenda(agenda.map((x,j)=>j===i?{...x,done:e.target.checked}:x))}/> Hoàn thành</label><button type="button" aria-label={'Xóa mục '+(i+1)} onClick={()=>setAgenda(agenda.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>)}<button type="button" disabled={agenda.length>=30} onClick={()=>setAgenda([...agenda,{name:'',minutes:15,notes:'',done:false}])}><Plus size={16}/> Thêm nội dung</button><label>Kết luận<textarea name="conclusion" defaultValue={meeting.conclusion}/></label><label>Hành động tiếp theo<textarea name="actions" defaultValue={meeting.actions}/></label><label><input name="closed" type="checkbox" defaultChecked={meeting.closed}/> Chốt buổi</label><button className="primary" type="submit">Lưu nội dung buổi</button></fieldset></form>;
}
