import {useCallback,useEffect,useRef,useState} from 'react';

type Catalog={id:string;name:string;project:string};
type Item={id:string;unit:string;name:string;code:string;tracking_code?:string};
type Table={id:string;kind:string;header:number;rows:string[][]};
type Payload={schema:{file:string;order:{text?:string;heading?:boolean;table?:string}[];tables:Table[]};values:Record<string,string>;origins:Record<string,string>;rows:Record<string,number>;locked:string[];conflicts:{cell:string;text:string;file:string}[];stale:boolean;history:{id:string;at?:string;by?:string;label:string}[];master?:{revision:number;status:string;history:{action:string;at:string;by:string;reason:string;cells:Record<string,string>}[]};record?:{id:string;status:string;versions:{number:number}[];self_reflection?:{revision:number;status:string};self_submissions?:{submission_id:string;submitted_at:string;steps:Record<string,{note:string;decision:string}>;form_cells?:Record<string,string>}[]}};
type Props={units:Catalog[];items:Item[];api:(op:string,data?:unknown)=>Promise<any>;command:(op:string,data:Record<string,unknown>)=>Promise<boolean>;canEdit:boolean;canReview:boolean;open:(id:string)=>void};
const labels:Record<string,string>={draft:'Bản đang chỉnh · Chưa duyệt',returned:'Được trả lại để bổ sung',submitted:'Đã gửi · Chờ duyệt',accepted:'Đã duyệt',save:'Lưu bổ sung',submit:'Gửi bổ sung',accept:'Duyệt bổ sung',return:'Trả lại'};

export default function FormSummary({units,items,api,command,canEdit,canReview,open}:Props){
 const [unit,setUnit]=useState(units.length===1?units[0].id:'');const [form,setForm]=useState('01');const [mode,setMode]=useState('draft');const [iid,setIid]=useState('');
 const [data,setData]=useState<Payload|null>(null);const [edits,setEdits]=useState<Record<string,string>>({});const [rows,setRows]=useState<Record<string,number>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');
 const apiRef=useRef(api);apiRef.current=api;
 const root=useRef<HTMLDivElement>(null);const generation=useRef(0);const dirty=Object.keys(edits).length>0;const available=items.filter(r=>r.unit===unit);const selected=available.find(r=>r.id===iid);
 const load=useCallback(async()=>{const id=++generation.current;if(!unit||(form==='02'&&!iid)){setData(null);return;}setBusy(true);setError('');try{const value=await apiRef.current('form-summary?'+new URLSearchParams({unit,form,mode,initiative:iid}));if(id===generation.current){setData(value);setRows(value.rows);}}catch(e){if(id===generation.current){setData(null);setError(e instanceof Error?e.message:'Không tải được biểu mẫu');}}finally{if(id===generation.current)setBusy(false);}},[unit,form,mode,iid]);
 useEffect(()=>{setEdits({});void load();return()=>{generation.current++;};},[load]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 useEffect(()=>{const guard=(e:MouseEvent)=>{if(dirty&&!root.current?.contains(e.target as Node)&&(e.target as Element).closest('button,a,select')&&!window.confirm('Có nội dung biểu mẫu chưa lưu. Bỏ thay đổi và rời trang?')){e.preventDefault();e.stopPropagation();}};document.addEventListener('click',guard,true);return()=>document.removeEventListener('click',guard,true);},[dirty]);
 const change=(fn:()=>void)=>{if(!dirty||window.confirm('Bỏ các ô chưa lưu để đổi biểu mẫu?')){setEdits({});fn();}};
 const reflection=data?.record?.self_reflection;const status=form==='01'?data?.master?.status:reflection?.status;
 const editable=canEdit&&mode==='draft'&&!data?.stale&&!busy&&status!=='submitted'&&(form==='01'||(!['accepted'].includes(status||'')&&!['submitted','complete'].includes(data?.record?.status||'')));
 const context=()=>({id:iid,base_version:data!.record!.versions.at(-1)!.number,revision:reflection?.revision||0});
 const save=async()=>{if(!data||!editable||!dirty)return;setBusy(true);try{const ok=await command(form==='01'?'master-form':'reflection',form==='01'?{unit,revision:data.master?.revision||0,action:'save',cells:edits}:{...context(),action:'form-cells',cells:edits});if(ok){setEdits({});await load();}}finally{setBusy(false);}};
 const masterAction=async(action:string)=>{if(!data)return;setBusy(true);try{if(await command('master-form',{unit,revision:data.master?.revision||0,action,reason}))await load();}finally{setBusy(false);}};
 const cellLabel=(key:string)=>{const [t,r,c]=key.split(':').map(Number);const table=data?.schema.tables[t];return table?.kind==='fields'?table.rows[r]?.[0]:`${table?.rows[0]?.[c]||'Nội dung'} · dòng ${r}`;};
 const fixed=(t:Table,r:number,c:number)=>t.kind==='static'||r<t.header||(t.kind==='fields'&&c===0)||(form==='01'&&(t.id==='4'||(t.id==='2'&&r===0)))||(form==='02'&&((t.id==='2'&&[0,1].includes(r))||(['3','7'].includes(t.id)&&c===0)))||data?.locked.includes(`${t.id}:${r}:${c}`);
 return <div className="vc-form-summary" ref={root}>
  <div className="vc-filters"><label>Đơn vị<select value={unit} disabled={busy} onChange={e=>change(()=>{setUnit(e.target.value);setIid('');})}><option value="">Chọn đơn vị</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Biểu mẫu<select value={form} disabled={busy} onChange={e=>change(()=>setForm(e.target.value))}><option value="01">Biểu mẫu 01 · Tổng hợp đơn vị</option><option value="02">Biểu mẫu 02 · Chi tiết sáng kiến</option></select></label><label>Phiên bản nội dung<select value={mode} disabled={busy} onChange={e=>change(()=>setMode(e.target.value))}><option value="draft">Bản đơn vị đang chỉnh</option><option value="approved">Bản nguồn và hiệu chỉnh đã duyệt</option></select></label></div>
  {form==='02'&&<label>Sáng kiến<select value={selected?.id||''} disabled={busy} onChange={e=>change(()=>setIid(e.target.value))}><option value="">Chọn sáng kiến</option>{available.map(r=><option key={r.id} value={r.id}>{r.tracking_code||r.code} · {r.name}</option>)}</select></label>}
  {error&&<div className="vc-error" role="alert">{error}<button onClick={()=>void load()}>Thử lại</button></div>}{busy&&<p role="status">Đang tải / lưu biểu mẫu…</p>}
  {!unit&&<p>Chọn đơn vị để xem biểu mẫu tổng hợp.</p>}{unit&&form==='02'&&!available.length&&<p>Đơn vị chưa có sáng kiến đã tổng hợp.</p>}
  {data&&<><div className="vc-info"><strong>{mode==='draft'?(form==='01'?'Bản đơn vị đang chỉnh · gồm phần chưa duyệt':labels[status||'draft']):'Nội dung nguồn và phần hiệu chỉnh đã được duyệt'}</strong><p>Nội dung lấy từ tài liệu nguồn chưa được tự coi là đã duyệt. Ô tự cập nhật từ 8 bước được khóa nhập tại đây; các ô còn lại có thể bổ sung. Phần chưa có thông tin để trống.</p>{data.stale&&<p>Nguồn đã đổi phiên bản. Bản tự soi cũ chưa được đưa vào tổng hợp; mở hồ sơ để đối chiếu và bắt đầu đợt mới.</p>}{form==='02'&&<button onClick={()=>change(()=>open(iid))}>Mở tự soi 8 bước / gửi bản tự soi</button>}</div>
  {data.schema.order.map((entry,index)=>entry.table!==undefined?(()=>{const t=data.schema.tables[Number(entry.table)];const count=rows[t.id]||t.rows.length;return <section className="vc-form-table-section" key={index}><div className="vc-table"><table className={t.kind==='fields'?'vc-form-fields':''}><tbody>{Array.from({length:count},(_,r)=><tr key={r}>{Array.from({length:t.rows[0].length},(_,c)=>{const key=`${t.id}:${r}:${c}`;const template=t.rows[r]?.[c]||'';const readonly=fixed(t,r,c);const isLabel=t.kind==='static'||r<t.header||(t.kind==='fields'&&c===0)||(form==='02'&&['3','7'].includes(t.id)&&c===0);const value=edits[key]??data.values[key]??(isLabel?template:'');const Cell=r<t.header?'th':'td';return <Cell key={c}><div className="vc-form-cell">{editable&&!readonly?<textarea aria-label={`${t.rows[0][c]||'Nội dung'} · bảng ${Number(t.id)+1}, dòng ${r+1}`} value={value} placeholder={template||'Chưa có thông tin'} onChange={e=>setEdits({...edits,[key]:e.target.value})}/>:<div className="vc-form-value">{value||'—'}</div>}{data.origins[key]&&<small>{data.origins[key]}</small>}</div></Cell>;})}</tr>)}</tbody></table></div>{editable&&((form==='01'&&['5','6'].includes(t.id))||(form==='02'&&['4','5','6'].includes(t.id)))&&count<200&&<button onClick={()=>{setRows({...rows,[t.id]:count+1});setEdits({...edits,[`${t.id}:${count}:0`]:String(count)});}}>Thêm dòng</button>}</section>;})():entry.heading?<h2 className="vc-form-heading" key={index}>{entry.text}</h2>:<p key={index}>{entry.text}</p>)}
  {!!data.conflicts.length&&<details className="vc-card"><summary>Các nội dung nguồn khác nhau cần đối chiếu ({data.conflicts.length})</summary>{data.conflicts.map((x,i)=><p key={i}><b>{x.file} · {cellLabel(x.cell)}</b><br/>{x.text}</p>)}</details>}
  <div className="vc-row vc-form-save"><span>{dirty?'Có nội dung chưa lưu':'Đang hiển thị dữ liệu đã lưu'}</span><button className="primary" disabled={!editable||!dirty} onClick={()=>void save()}>Lưu phần bổ sung biểu mẫu</button>{form==='01'&&canEdit&&mode==='draft'&&<button disabled={busy||dirty||status==='submitted'||!data.master||status==='accepted'} onClick={()=>void masterAction('submit')}>Gửi phần bổ sung Biểu mẫu 01</button>}</div>
  {form==='01'&&canReview&&status==='submitted'&&<section className="vc-card"><h3>Duyệt phần bổ sung cấp đơn vị</h3><p>Nội dung tự soi của từng sáng kiến được duyệt trong hồ sơ sáng kiến.</p><label>Căn cứ quyết định<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()} onClick={()=>void masterAction('return')}>Trả lại</button> <button disabled={busy||!reason.trim()} onClick={()=>void masterAction('accept')}>Duyệt phần bổ sung</button></section>}
  <details className="vc-card"><summary>Lịch sử hiệu chỉnh</summary>{data.history.length?data.history.map(x=><p key={x.id}>{x.at?new Date(x.at).toLocaleString('vi-VN'):''} · {x.by?.includes('@')?x.by:'Đơn vị'} · {labels[x.label]||x.label}</p>):<p>Chưa có lần gửi hoặc hiệu chỉnh biểu mẫu.</p>}{data.master?.history.map((h,i)=><details key={i}><summary>{labels[h.action]||h.action} · {new Date(h.at).toLocaleString('vi-VN')}</summary><p>{h.reason}</p>{Object.entries(h.cells).map(([key,text])=><p key={key}><b>{cellLabel(key)}</b>: {text||'(Để trống)'}</p>)}</details>)}{data.record?.self_submissions?.map(s=><details key={s.submission_id}><summary>Bản tự soi · {new Date(s.submitted_at).toLocaleString('vi-VN')}</summary>{Object.entries(s.steps).map(([step,value])=><p key={step}>Bước {step}: {value.note}</p>)}{Object.entries(s.form_cells||{}).map(([key,text])=><p key={key}>{cellLabel(key)}: {text||'(Để trống)'}</p>)}</details>)}</details>
  </>}
 </div>;
}
